### ISSUE TITLE
PlayerController

### ISSUE THREAD

**Issue by Son1kXDev** [Son1kXDev/5opkagame2d#1]
Простой скрипт управления игроком в 2d.

**Comment by Son1kXDev** [comment]
Сделал простейший PlayerController.cs и PlayerInputController.cs

https://github.com/Son1kXDev/5opkagame2d/assets/106654105/a4d7ce71-a140-4d1b-a462-47ce71b641f5

**Comment by NVWgamedev** [comment]
ну двойной прыжок можно как способность сделать, но не по дефолту. И надо убрать этот эффект льда (умное слово забыл). Инерция вспомнил

ps а бля это он так высоко скачет а не двойной прыжок

ps ps хотя не скольжение можно оставить и ебануть анимацию торможения

**Comment by NVWgamedev** [comment]
Исправь прикол что этот дурачек к стене прилепает, а то косплеит человека паука
