### ISSUE TITLE
Параллакс эффект

### ISSUE THREAD

**Issue by NVWgamedev** [Son1kXDev/5opkagame2d#4]
Сделай его более гибким (чтобы не было фиксированного количество фонов - просто создать лист для них. Скорость движения фона, относительно игрока, будет зависеть от положения в листе)

**Comment by Son1kXDev** [comment]
ParallaxBehaviour - Добавляется на объект который будет следовать за игроком (либо родительский объект, содержащий в себе все объекты, которые будут следовать).

![Image](https://github.com/Son1kXDev/5opkagame2d/assets/106654105/ecc20418-b539-46b6-a806-c395d1d5a176)

Для каждого ParallaxBehaviour отдельно настраивается FollowingTarget (цель), Horizontal & Vertical Parallax Strength (сила следования по горизонтали и вертикали)
