### ISSUE TITLE
Враждебные НПС База

### ISSUE THREAD

**Issue by NVWgamedev** [Son1kXDev/5opkagame2d#8]
пока нет спрайтов самих врагов и оружия так что можешь юзать примитивы, щас главное чтобы они замечали игрока и пытались дать ему пизды (надо сделать каркас). Будет два класса: Дальники и ближники, от этого будет зависеть их атаки (или как ебланы несутся на игрока или вкрысу стреляют). В режиме покоя хз либо пусть стоят как столбы или можно сделать им патрульные точки. Это пока все что надо, если хочешь выдумай еще че нибудь.

**Comment by Son1kXDev** [comment]
Сделал базового противника, умеет патрулировать, преследовать игрока и атаковать. Все растояния для патрулирования, преследования и атаки настраиваются. Поэтому он может как ближником, так и дальником, останется только сделать разные анимации атаки (удар мечем, стрельба из лука и т.д).
